sudo: false
cache: pip
language: python

branches:
  only:
    - master
    - development

before_install:
  - pip install poetry

install:
  - poetry --version
  - poetry install -vvv --develop=susy_cross_section

stages:
  - test
  - typecheck
#  - linting

script:
  - nosetests -s -d
  - coveralls

jobs:
  include:
    - python: "2.7"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial

    - stage: typecheck
      python: "3.6"
      script:
        - mypy -p susy_cross_section
#    - stage: linting
#      python: "3.6"
#      script:
#        - flake8 susy_cross_section
